//----- ラインセンサ -----//
#define LINE_GREEN_PIN 15
#define LINE_SENSOR_THRESHOLD_1 230
#define LINE_SENSOR_THRESHOLD_2 230
#define LINE_SENSOR_THRESHOLD_3 250
#define LINE_SENSOR_THRESHOLD_4 230
#define LINE_SENSOR_THRESHOLD_5 230
#define LINE_SENSOR_PIN_1 A3
#define LINE_SENSOR_PIN_2 A5
#define LINE_SENSOR_PIN_3 A1
#define LINE_SENSOR_PIN_4 A7
#define LINE_SENSOR_PIN_5 A9

//----- カラーセンサ -----//
#define COLOR_SENSOR_RED_PIN 14
#define COLOR_SENSOR_GREEN_PIN 15
#define COLOR_SENSOR_BLUE_PIN 15

#define COLOR_SENSOR_L_READER_PIN A4
#define COLOR_SENSOR_R_READER_PIN A8

#define THRESHOLD_RED 150
#define THRESHOLD_GREEN 1

//----- モータ -----//
#define MOTOR_L_FRONT_PIN 3
#define MOTOR_L_BACK_PIN 2

#define MOTOR_R_FRONT_PIN 4
#define MOTOR_R_BACK_PIN 5

//----- ロータリーエンコーダ -----//
#define ROTARY_ENCODER_READER_PIN -1
#define STRAIGHT_LENGH 30
#define BACK_LENGH 10
#define REN_LENGTH 10
#define THRESHOLD_ROTARY_ENCODER 990
#define IKKAITEN 19

//----- 速度 -----//
#define SPEED 100
#define SLOW_SPEED 80

//----- その他 -----//
#define THRESHOLD_REN 50
